version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_STATS_DB_URL=jdbc:postgresql://stats-db:5432/stats_db
      - POSTGRES_STATS_USER=root
      - POSTGRES_STATS_PASSWORD=root

  stats-db:
    image: postgres:14.3-alpine
    container_name: stats-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_db:/var/lib/postgresql/data_stats

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - POSTGRES_EWM_DB_URL=jdbc:postgresql://ewm-db:5433/ewm_db
      - POSTGRES_EWM_USER=root
      - POSTGRES_EWM_PASSWORD=root

  ewm-db:
    image: postgres:14.3-alpine
    container_name: ewm-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewm_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_db:/var/lib/postgresql/data_emv